language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - wget https://getcomposer.org/composer.phar
  - php composer.phar install --prefer-source

script:
  - vendor/bin/atoum --test-ext
